const GET_USER_REQUEST = "GET_USER_REQUEST";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_REQUEST_FAILED = "GET_REQUEST_FAILED";

export { GET_REQUEST_FAILED, GET_USER_REQUEST, GET_USER_SUCCESS };
